import {
  Budget,
  DashboardStats,
  ParsedReceipt,
  Receipt,
  WeeklyReport,
  User,
  Category,
} from "./types";

export const mockUser: User = {
  id: "user-123",
  name: "Alex Rivera",
  email: "alex.rivera@example.com",
  avatarUrl: "https://api.dicebear.com/9.x/identicon/svg?seed=alex",
};

export const categories: Category[] = [
  { id: "groceries", name: "Groceries", icon: "🛒", color: "emerald" },
  { id: "dining", name: "Dining", icon: "🍽️", color: "sky" },
  { id: "transport", name: "Transport", icon: "🚌", color: "amber" },
  { id: "utilities", name: "Utilities", icon: "💡", color: "violet" },
  { id: "shopping", name: "Shopping", icon: "🛍️", color: "pink" },
  { id: "health", name: "Health", icon: "🩺", color: "rose" },
];

export const receipts: Receipt[] = [
  {
    id: "rct-1001",
    store: "Fresh Mart",
    date: "2025-01-05",
    categoryId: "groceries",
    total: 142.34,
    tax: 8.54,
    status: "processed",
    anomalyFlags: ["spike"],
    imageUrl: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=60",
    ocrConfidence: 0.97,
    rawText:
      "Fresh Mart\nJan 5 2025\nApples 4.50\nChicken 24.99\nTotal 142.34",
    items: [
      {
        id: "itm-1",
        description: "Organic apples",
        quantity: 2,
        unitPrice: 4.5,
        total: 9,
        categoryId: "groceries",
      },
      {
        id: "itm-2",
        description: "Free-range chicken",
        quantity: 1,
        unitPrice: 24.99,
        total: 24.99,
        categoryId: "groceries",
      },
      {
        id: "itm-3",
        description: "Weekly groceries",
        quantity: 1,
        unitPrice: 108.35,
        total: 108.35,
        categoryId: "groceries",
      },
    ],
  },
  {
    id: "rct-1002",
    store: "Blue Diner",
    date: "2025-01-08",
    categoryId: "dining",
    total: 62.15,
    tax: 3.74,
    status: "processed",
    anomalyFlags: [],
    imageUrl: "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=600&q=60",
    ocrConfidence: 0.94,
    rawText: "Blue Diner\nJan 8 2025\nDinner for two\nTotal 62.15",
    items: [
      {
        id: "itm-4",
        description: "Entrees",
        quantity: 2,
        unitPrice: 18,
        total: 36,
        categoryId: "dining",
      },
      {
        id: "itm-5",
        description: "Desserts",
        quantity: 2,
        unitPrice: 6,
        total: 12,
        categoryId: "dining",
      },
      {
        id: "itm-6",
        description: "Drinks",
        quantity: 2,
        unitPrice: 7.07,
        total: 14.14,
        categoryId: "dining",
      },
    ],
  },
  {
    id: "rct-1003",
    store: "Metro Transit",
    date: "2025-01-09",
    categoryId: "transport",
    total: 45.5,
    tax: 0,
    status: "processed",
    anomalyFlags: [],
    imageUrl: "https://images.unsplash.com/photo-1541417904950-b855846fe074?auto=format&fit=crop&w=600&q=60",
    ocrConfidence: 0.9,
    rawText: "Metro Transit pass\nJan 9 2025\nTotal 45.50",
    items: [
      {
        id: "itm-7",
        description: "Monthly pass",
        quantity: 1,
        unitPrice: 45.5,
        total: 45.5,
        categoryId: "transport",
      },
    ],
  },
  {
    id: "rct-1004",
    store: "Bright Utilities",
    date: "2025-01-10",
    categoryId: "utilities",
    total: 128.9,
    tax: 0,
    status: "processed",
    anomalyFlags: ["ocr_mismatch"],
    imageUrl: "https://images.unsplash.com/photo-1509395176047-4a66953fd231?auto=format&fit=crop&w=600&q=60",
    ocrConfidence: 0.81,
    rawText: "Electric utility bill\nTotal 128.90",
    items: [
      {
        id: "itm-8",
        description: "Electricity",
        quantity: 1,
        unitPrice: 128.9,
        total: 128.9,
        categoryId: "utilities",
      },
    ],
  },
  {
    id: "rct-1005",
    store: "Healthy Life Pharmacy",
    date: "2025-01-12",
    categoryId: "health",
    total: 78.25,
    tax: 2.34,
    status: "flagged",
    anomalyFlags: ["duplicate"],
    imageUrl: "https://images.unsplash.com/photo-1587854692152-8d3d86fc0b1c?auto=format&fit=crop&w=600&q=60",
    ocrConfidence: 0.86,
    rawText: "Pharmacy purchase\nTotal 78.25",
    items: [
      {
        id: "itm-9",
        description: "Vitamins",
        quantity: 1,
        unitPrice: 34.5,
        total: 34.5,
        categoryId: "health",
      },
      {
        id: "itm-10",
        description: "Prescription",
        quantity: 1,
        unitPrice: 43.75,
        total: 43.75,
        categoryId: "health",
      },
    ],
  },
  {
    id: "rct-1006",
    store: "Urban Outfitters",
    date: "2025-01-13",
    categoryId: "shopping",
    total: 156.75,
    tax: 9.4,
    status: "processed",
    anomalyFlags: [],
    imageUrl: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=60",
    ocrConfidence: 0.92,
    rawText: "Clothing purchase\nTotal 156.75",
    items: [
      {
        id: "itm-11",
        description: "Jacket",
        quantity: 1,
        unitPrice: 98.5,
        total: 98.5,
        categoryId: "shopping",
      },
      {
        id: "itm-12",
        description: "Accessories",
        quantity: 2,
        unitPrice: 29.12,
        total: 58.25,
        categoryId: "shopping",
      },
    ],
  },
  {
    id: "rct-1007",
    store: "Fresh Mart",
    date: "2025-01-15",
    categoryId: "groceries",
    total: 96.43,
    tax: 5.21,
    status: "processed",
    anomalyFlags: [],
    imageUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=600&q=60",
    ocrConfidence: 0.95,
    rawText: "Groceries\nTotal 96.43",
    items: [
      {
        id: "itm-13",
        description: "Produce",
        quantity: 1,
        unitPrice: 32.4,
        total: 32.4,
        categoryId: "groceries",
      },
      {
        id: "itm-14",
        description: "Pantry staples",
        quantity: 1,
        unitPrice: 64.03,
        total: 64.03,
        categoryId: "groceries",
      },
    ],
  },
  {
    id: "rct-1008",
    store: "Green Cab",
    date: "2025-01-17",
    categoryId: "transport",
    total: 24.8,
    tax: 0,
    status: "processed",
    anomalyFlags: ["spike"],
    imageUrl: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=600&q=60",
    ocrConfidence: 0.89,
    rawText: "Ride share\nTotal 24.80",
    items: [
      {
        id: "itm-15",
        description: "Airport ride",
        quantity: 1,
        unitPrice: 24.8,
        total: 24.8,
        categoryId: "transport",
      },
    ],
  },
];

export const budgets: Budget[] = [
  {
    id: "bdg-1",
    categoryId: "groceries",
    categoryName: "Groceries",
    limit: 600,
    spent: 420,
    month: "2025-01",
  },
  {
    id: "bdg-2",
    categoryId: "dining",
    categoryName: "Dining",
    limit: 250,
    spent: 180,
    month: "2025-01",
  },
  {
    id: "bdg-3",
    categoryId: "transport",
    categoryName: "Transport",
    limit: 180,
    spent: 120,
    month: "2025-01",
  },
  {
    id: "bdg-4",
    categoryId: "utilities",
    categoryName: "Utilities",
    limit: 200,
    spent: 128.9,
    month: "2025-01",
  },
  {
    id: "bdg-5",
    categoryId: "shopping",
    categoryName: "Shopping",
    limit: 350,
    spent: 156.75,
    month: "2025-01",
  },
  {
    id: "bdg-6",
    categoryId: "health",
    categoryName: "Health",
    limit: 150,
    spent: 78.25,
    month: "2025-01",
  },
  {
    id: "bdg-7",
    categoryId: "groceries",
    categoryName: "Groceries",
    limit: 550,
    spent: 210,
    month: "2024-12",
  },
];

export const dashboardStats: DashboardStats = {
  totalSpentThisMonth: 736.12,
  remainingBudget: 993.88,
  receiptsThisMonth: receipts.length,
  anomaliesDetected: receipts.filter((r) => r.anomalyFlags.length > 0).length,
  spendingByCategory: [
    { categoryId: "groceries", categoryName: "Groceries", amount: 238.77 },
    { categoryId: "dining", categoryName: "Dining", amount: 62.15 },
    { categoryId: "transport", categoryName: "Transport", amount: 70.3 },
    { categoryId: "utilities", categoryName: "Utilities", amount: 128.9 },
    { categoryId: "shopping", categoryName: "Shopping", amount: 156.75 },
    { categoryId: "health", categoryName: "Health", amount: 78.25 },
  ],
  spendingOverTime: [
    { date: "2025-01-03", amount: 120.35 },
    { date: "2025-01-05", amount: 142.34 },
    { date: "2025-01-08", amount: 62.15 },
    { date: "2025-01-12", amount: 78.25 },
    { date: "2025-01-15", amount: 96.43 },
    { date: "2025-01-17", amount: 24.8 },
  ],
};

export const weeklyReport: WeeklyReport = {
  weekStart: "2025-01-06",
  weekEnd: "2025-01-12",
  totalSpent: 314.8,
  receiptCount: 4,
  anomaliesCount: 1,
  highlights: [
    {
      title: "Biggest category: Groceries",
      description: "Groceries led spend with $142.34 at Fresh Mart.",
      type: "info",
    },
    {
      title: "Largest receipt",
      description: "$142.34 at Fresh Mart on Jan 5, 2025.",
      type: "success",
    },
    {
      title: "Potential anomaly",
      description: "Duplicate detected on Healthy Life Pharmacy receipt.",
      type: "warning",
    },
  ],
  receipts: receipts.slice(0, 5),
};

export const parsedUploadReceipt: ParsedReceipt = {
  id: "rct-2001",
  store: "Corner Market",
  date: "2025-01-18",
  total: 54.22,
  tax: 3.14,
  categorySuggestions: ["Groceries", "Snacks"],
  status: "processed",
  anomalyFlags: [],
};
